name: Emit Release Event to Dependents

on:
  release:
    types:
      - created
jobs:
  get_dependents:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Set matrix values from dependents list
        run: |
          echo "::set-output name=matrix::$(cat .dependents.json)"
      - name: sleep for 5 minutes for PyPI update
        run: sleep 300s
        shell: bash

  emit_event_to_dependent:
    runs-on: ubuntu-latest
    needs: get_dependents
    strategy:
      matrix: ${{fromJson(needs.get_dependents.outputs.matrix)}}
    steps:
      - name: Update dependent
        env:
          DISPATCH_REPO: ${{ matrix.repository }}
          DEPS_TOKEN: ${{ secrets.DEPS_UPDATING }}
        run: |
          curl -X POST https://api.github.com/repos/$DISPATCH_REPO/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -d '{"event_type": "new_dependency_version", "client_payload": {"version": "${{ github.event.tag_name }}", "dependency_name": "${{ github.event.repository.name }}"}}' \
          -u ladybugbot:$DEPS_TOKEN
