name: Update Github Workflow Templates

on:
  push:
    branches:
      - master
jobs:
  list_organization_repositories:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - id: set-matrix
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=matrix::$(python scripts/list_organization_repositories.py)"

  update_repository_workflow_templates:
    name: "Check Event"
    runs-on: ubuntu-latest
    needs: list_organization_repositories
    strategy:
      matrix: ${{fromJson(needs.list_organization_repositories.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Update Repository
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/update_repository_workflow_templates.py ${{ matrix.repository }}
